name: OrangeWallet
description: A wallet for Nervos

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  fluintl: ^0.1.3
  flutter_secure_storage: ^3.2.1+1
  shared_preferences: ^0.5.1+2
  encrypt: ^2.2.0
  provide: ^1.0.2
  flutter_spinkit: ^3.1.0
  qr_flutter: ^2.0.0+51
  path_provider: ^1.0.0
  ckbcore:
    git:
      url: https://github.com/OrangeWallet/ckbcore.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
